name: Deploy by Parag

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }} # Use the converted OpenSSH private key stored in GitHub secrets
        port: ${{ secrets.SERVER_PORT }} # Default SSH port is 22
        script: |
          cd ~
          cd /var/www/html/laravel_ci_cd
          git pull origin master
          php artisan optimize:clear
